# Generated by Django 4.2.1 on 2023-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=256)),
                ('post_body', models.TextField()),
                ('post_image', models.CharField(max_length=256)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('author_id', models.CharField(max_length=256)),
            ],
        ),
    ]
